INSERT INTO `area` VALUES (3, '010', 'ACOPIO', '0', NULL, NULL);
INSERT INTO `area` VALUES (4, '012', 'EMPAQUE', '0', NULL, NULL);
INSERT INTO `area` VALUES (5, '011', 'MANO DE OBRA INDIRECTA', '0', NULL, NULL);
