INSERT INTO `linea` VALUES (1, 'LINEA 01');
INSERT INTO `linea` VALUES (3, 'LINEA 03');
INSERT INTO `linea` VALUES (4, 'LINEA 02');
INSERT INTO `linea` VALUES (5, 'LINEA 04');
INSERT INTO `linea` VALUES (6, 'LINEA 05');
INSERT INTO `linea` VALUES (7, 'LINEA 06');
INSERT INTO `linea` VALUES (8, 'ÁREAS DIVERSAS');
INSERT INTO `linea` VALUES (10, 'SIN LINEA');
INSERT INTO `linea` VALUES (12, 'clamshell');
