INSERT INTO `linea` VALUES (1, 'LINEA 01', 7);
INSERT INTO `linea` VALUES (3, 'LINEA 03', 7);
INSERT INTO `linea` VALUES (4, 'LINEA 02', 7);
INSERT INTO `linea` VALUES (5, 'LINEA 04', 7);
INSERT INTO `linea` VALUES (6, 'LINEA 05', 8);
INSERT INTO `linea` VALUES (7, 'LINEA 06', 8);
INSERT INTO `linea` VALUES (8, 'ÁREAS DIVERSAS', 7);
INSERT INTO `linea` VALUES (10, 'SIN LINEA', 7);
INSERT INTO `linea` VALUES (12, 'clamshell', 12);
